version: "3.9"
    
services:
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: "on-failure"
    environment:
      MYSQL_ROOT_PASSWORD: dbpassword
      MYSQL_DATABASE: wordpress_local
      MYSQL_USER: wordpress_db_user
      MYSQL_PASSWORD: wordpress_db_password
    ports:
      - 4306:3306
    platform: linux/x86_64
    
  wordpress:
    container_name: wordpress-plugin-dev
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./plugins:/var/www/html/wp-content/plugins
      - ../okdork-theme-2023:/var/www/html/wp-content/themes/okdork-theme-2023
    ports:
      - "8000:80"
    restart: "on-failure"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: wordpress_db_user
      WORDPRESS_DB_PASSWORD: wordpress_db_password
      WORDPRESS_DB_NAME: wordpress_local
      WORDPRESS_DEBUG: true
volumes:
  db_data: {}